export const atividades = [
    {
        nome: "Caixa Sensorial com Materiais Variados",
        descricao: "Exploração tátil com caixa ou bacia preenchida com diferentes materiais (arroz, feijão, areia cinética, algodão) e objetos escondidos para encontrar.",
        como_fazer: "Encha a caixa com um ou mais materiais. Esconda objetos dentro e convide a criança a explorar com as mãos. Não force o contato — deixe que ela se aproxime no próprio ritmo. Introduza novos materiais gradualmente.",
        faixa_etaria: { min: 2, max: 8 },
        nivel_tea: [1, 2, 3],
        beneficios: ["integracao_sensorial", "regulacao_emocional", "atencao", "reducao_aversao_tatil"],
        evitar_se: ["hipersensibilidade_tatil_severa"],
        nivel_barulho: "baixo",
        nivel_baguncia: "medio",
        tempo_minutos: 25,
        materiais: ["caixa ou bacia de plastico", "arroz cru", "feijao", "areia cinetica", "algodao", "objetos pequenos escondidos"],
        areas_interesse: ["sensorial", "descoberta"],
        objetivos: ["exploracao_sensorial", "tolerancia_tatil", "curiosidade"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["toque", "texturas", "calmo", "descoberta"]
    },

    {
        nome: "Pintura com os Dedos ou Pés",
        descricao: "Atividade de expressão criativa usando tinta lavável atóxica com dedos, palmas, cotovelos ou pés sobre papel grande.",
        como_fazer: "Espalhe papel no chão ou mesa. Ofereça tinta em potinhos e incentive a criança a explorar livremente. Comece pintando junto para encorajar. Para crianças com aversão à sujeira, comece com tinta dentro de saco plástico fechado.",
        faixa_etaria: { min: 2, max: 7 },
        nivel_tea: [1, 2],
        beneficios: ["integracao_sensorial", "coordenacao_motora_fina", "expressao_emocional", "consciencia_corporal"],
        evitar_se: ["hipersensibilidade_tatil_severa", "aversao_intensa_a_sujeira"],
        nivel_barulho: "baixo",
        nivel_baguncia: "alto",
        tempo_minutos: 30,
        materiais: ["tinta lavavel atoxica", "papel kraft ou A3 ou papelao", "toalha umida", "avental"],
        areas_interesse: ["artes", "sensorial"],
        objetivos: ["expressao_criativa", "exploracao_sensorial", "consciencia_corporal"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["toque", "criatividade", "cores", "expressao"]
    },

    {
        nome: "Massinha Caseira com Aromas e Texturas",
        descricao: "Preparo e exploração de massinha caseira aromatizada com essências (lavanda, baunilha, laranja), estimulando o tato e o olfato simultaneamente.",
        como_fazer: "Misture farinha, sal, corante e essência. Adicione água aos poucos até obter massa maleável. Ofereça porções com texturas diferentes e deixe a criança explorar: espremer, rolar, cortar com moldes.",
        faixa_etaria: { min: 2, max: 8 },
        nivel_tea: [1, 2, 3],
        beneficios: ["estimulacao_tatil", "estimulacao_olfativa", "forcamento_muscular_maos", "concentracao", "autorregulacao"],
        evitar_se: ["hipersensibilidade_olfativa_severa", "comportamento_de_levar_tudo_a_boca_sem_supervisao"],
        nivel_barulho: "baixo",
        nivel_baguncia: "medio",
        tempo_minutos: 40,
        materiais: ["farinha de trigo", "sal", "agua morna", "essencias aromaticas", "corante alimenticio", "oleo de cozinha"],
        areas_interesse: ["sensorial", "culinaria"],
        objetivos: ["exploracao_sensorial_multimodal", "fortalecimento_motor_fino", "autorregulacao"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["toque", "olfato", "calmo", "criatividade"]
    },

    {
        nome: "Banho Sensorial Lúdico",
        descricao: "Transformação do momento do banho em experiência sensorial positiva com bolinhas de gel, espuma colorida, gelo e brinquedos de borracha.",
        como_fazer: "Prepare a banheira com elementos surpresa apresentados um de cada vez. Comece com o que a criança já tolera e introduza novos elementos gradualmente. Nomeie tudo que for tocado: 'isso é frio', 'essa bolinha é escorregadia'.",
        faixa_etaria: { min: 2, max: 6 },
        nivel_tea: [1, 2, 3],
        beneficios: ["dessensibilizacao_tatil", "desenvolvimento_de_linguagem", "vinculo_com_cuidador", "regulacao_sensorial"],
        evitar_se: ["hipersensibilidade_tatil_severa_sem_acompanhamento_terapeutico"],
        nivel_barulho: "baixo",
        nivel_baguncia: "medio",
        tempo_minutos: 25,
        materiais: ["bolinhas de gel hidratante", "espuma de sabao colorida", "cubos de gelo coloridos", "brinquedos de borracha", "peneiras e copinhos"],
        areas_interesse: ["sensorial", "agua"],
        objetivos: ["dessensibilizacao_gradual", "nomeacao_de_sensacoes", "rotina_positiva"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["agua", "toque", "temperatura", "rotina"]
    },

    {
        nome: "Trilha de Obstáculos com Almofadas",
        descricao: "Percurso motor montado em casa com almofadas, colchonetes, tapetes e cadeiras para estimular equilíbrio, propriocepção e planejamento motor.",
        como_fazer: "Monte o percurso pela sala. A criança caminha sobre almofadas, rasteja sob cadeiras, pula entre tapetes. Faça junto para mostrar as etapas. Nomeie cada etapa com linguagem divertida: 'rasteja como lagarta!', 'pula como sapo!'.",
        faixa_etaria: { min: 2, max: 8 },
        nivel_tea: [1, 2],
        beneficios: ["equilibrio_dinamico", "propriocepcao", "planejamento_motor", "seguimento_de_instrucoes"],
        evitar_se: ["crises_de_agitacao_intensa", "dificuldade_motora_grave_sem_adaptacao"],
        nivel_barulho: "medio",
        nivel_baguncia: "medio",
        tempo_minutos: 28,
        materiais: ["almofadas", "colchonetes", "tapetes", "cadeiras", "fita adesiva colorida"],
        areas_interesse: ["movimento", "descoberta"],
        objetivos: ["coordenacao_motora_global", "consciencia_corporal", "atencao_e_instrucoes"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["movimento", "equilibrio", "brincadeira", "corpo"]
    },

    {
        nome: "Caminhar sobre a Linha",
        descricao: "Atividade de equilíbrio com fita adesiva colada no chão formando linhas retas, curvas ou em zigue-zague para a criança percorrer.",
        como_fazer: "Cole linhas no chão e peça que a criança caminhe sobre elas sem sair. Comece com linha reta e aumente a complexidade. Variações: caminhar de costas, de lado, com braços abertos, segurando objeto na cabeça. Use narrativa: 'a linha é uma ponte sobre o rio!'.",
        faixa_etaria: { min: 3, max: 9 },
        nivel_tea: [1, 2, 3],
        beneficios: ["equilibrio", "foco_visual", "controle_postural", "coordenacao_motora_global"],
        evitar_se: [],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 20,
        materiais: ["fita adesiva colorida"],
        areas_interesse: ["movimento", "faz_de_conta"],
        objetivos: ["equilibrio_estatico_e_dinamico", "controle_corporal", "foco_visual"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["equilibrio", "calmo", "simples", "corpo"]
    },

    {
        nome: "Saquinho de Equilíbrio na Cabeça",
        descricao: "Desafio lúdico de equilibrar um saquinho de pano com grãos sobre a cabeça enquanto caminha ou realiza pequenas tarefas.",
        como_fazer: "Mostre como equilibrar o saquinho na cabeça. Peça que caminhe de um ponto a outro sem deixar cair. Crie desafios progressivos: parar, agachar, contornar obstáculos. Adapte para ombro ou braço se houver sensibilidade.",
        faixa_etaria: { min: 3, max: 10 },
        nivel_tea: [1, 2],
        beneficios: ["equilibrio", "postura", "consciencia_proprioceptiva", "controle_de_impulsos"],
        evitar_se: ["hipersensibilidade_tatil_na_cabeca"],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 18,
        materiais: ["saquinho de pano com feijao ou arroz"],
        areas_interesse: ["movimento", "desafios"],
        objetivos: ["equilibrio_estatico_e_dinamico", "postura_ereta", "concentracao"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["equilibrio", "concentracao", "calmo", "corpo"]
    },

    {
        nome: "Pular nos Alvos Coloridos",
        descricao: "Atividade de coordenação e lateralidade com folhas coloridas no chão usadas como alvos para pular seguindo sequências e instruções.",
        como_fazer: "Espalhe os alvos no chão. Proponha desafios: 'pule no amarelo com dois pés', 'agora no azul com o pé direito'. Crie sequências para memorizar. Nomeie as cores antes de pular para trabalhar vocabulário simultaneamente.",
        faixa_etaria: { min: 3, max: 8 },
        nivel_tea: [1, 2],
        beneficios: ["coordenacao_motora_global", "lateralidade", "memoria_sequencial", "equilibrio_dinamico", "atencao"],
        evitar_se: [],
        nivel_barulho: "medio",
        nivel_baguncia: "baixo",
        tempo_minutos: 25,
        materiais: ["folhas de papel coloridas ou almofadas pequenas", "fita adesiva"],
        areas_interesse: ["movimento", "jogos"],
        objetivos: ["lateralidade", "sequenciamento", "coordenacao_motora"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["movimento", "cores", "memoria", "brincadeira"]
    },

    {
        nome: "Soprar com Canudinho",
        descricao: "Exercício orofacial lúdico em que a criança usa canudos para soprar bolinhas de papel, algodão ou penas sobre uma superfície.",
        como_fazer: "Coloque objetos leves sobre a mesa e desafie a criança a movê-los soprando pelo canudo. Crie metas: soprar até uma linha, marcar gol na caixinha. Varie a espessura dos canudos. Intercale com atividades de sucção.",
        faixa_etaria: { min: 2, max: 8 },
        nivel_tea: [1, 2, 3],
        beneficios: ["fortalecimento_orofacial", "controle_do_sopro", "pre_requisito_para_fala", "foco"],
        evitar_se: ["dificuldades_respiratorias_graves"],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 15,
        materiais: ["canudos de diferentes espessuras", "bolinhas de papel", "algodao", "penas", "caixa de papelao"],
        areas_interesse: ["fala", "jogos"],
        objetivos: ["fortalecimento_muscular_oral", "pre_requisitos_para_articulacao", "controle_respiratorio"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["fala", "sopro", "calmo", "simples"]
    },

    {
        nome: "Músicas com Gestos e Repetição",
        descricao: "Cantar músicas infantis repetitivas com gestos corporais correspondentes à letra para estimular linguagem, memória e atenção compartilhada.",
        como_fazer: "Cante a música realizando os gestos. Repita várias vezes — a repetição é fundamental. Pause antes da última palavra e espere que a criança complete. Comemore qualquer tentativa de vocalização. Escolha músicas de interesse da criança.",
        faixa_etaria: { min: 1, max: 7 },
        nivel_tea: [1, 2, 3],
        beneficios: ["desenvolvimento_de_vocabulario", "memoria_auditiva", "atencao_compartilhada", "ritmo_e_entonacao", "comunicacao_intencional"],
        evitar_se: ["hipersensibilidade_auditiva_severa"],
        nivel_barulho: "medio",
        nivel_baguncia: "baixo",
        tempo_minutos: 20,
        materiais: ["aparelho de som ou celular"],
        areas_interesse: ["musica", "movimento"],
        objetivos: ["estimulacao_da_linguagem_expressiva", "atencao_compartilhada", "imitacao_motora"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["fala", "musica", "repeticao", "vinculo"]
    },

    {
        nome: "Livros de Imagens com Narração Conjunta",
        descricao: "Leitura interativa de livros com imagens grandes, com apontamento, nomeação e perguntas simples para estimular vocabulário e atenção conjunta.",
        como_fazer: "Folheie o livro com calma. Aponte e nomeie as imagens. Faça perguntas simples: 'onde está a bola?', 'que cor é essa?'. Não exija respostas corretas. Crie um ritual: mesma hora e lugar. Com o tempo, deixe espaços para a criança 'contar' com gestos ou sons.",
        faixa_etaria: { min: 1, max: 7 },
        nivel_tea: [1, 2, 3],
        beneficios: ["desenvolvimento_de_vocabulario", "atencao_conjunta", "comunicacao_intencional", "sequenciamento_de_historias", "vinculo_com_cuidador"],
        evitar_se: [],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 15,
        materiais: ["livros com imagens grandes e coloridas"],
        areas_interesse: ["leitura", "historias"],
        objetivos: ["estimulacao_da_linguagem", "atencao_conjunta", "rotina_positiva"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["fala", "leitura", "calmo", "vinculo", "rotina"]
    },

    {
        nome: "Imitação de Sons do Cotidiano",
        descricao: "Estímulo à imitação vocal por meio de sons de animais e objetos cotidianos, usando figuras, brinquedos sonoros ou aplicativos.",
        como_fazer: "Mostre uma figura e produza o som correspondente. Aguarde alguns segundos olhando para a criança. Se ela vocalizar qualquer coisa, repita com entusiasmo. Crie uma 'chamada dos sons'. Valide qualquer aproximação sonora — não corrija diretamente, mas modele em seguida.",
        faixa_etaria: { min: 1, max: 6 },
        nivel_tea: [1, 2, 3],
        beneficios: ["imitacao_vocal", "vocabulario_inicial", "comunicacao_intencional", "atencao_e_contato_visual"],
        evitar_se: [],
        nivel_barulho: "medio",
        nivel_baguncia: "baixo",
        tempo_minutos: 15,
        materiais: ["figuras de animais e objetos", "brinquedos sonoros"],
        areas_interesse: ["fala", "animais"],
        objetivos: ["imitacao_vocal", "estimulacao_pre_verbal", "atencao_conjunta"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["fala", "sons", "imitacao", "simples"]
    },

    {
        nome: "Exploração Sensorial de Alimentos",
        descricao: "Exposição gradual e sem pressão a alimentos novos ou rejeitados antes da refeição principal, passando por etapas: olhar, cheirar, tocar, lamber e provar.",
        como_fazer: "Apresente o alimento em pratinho separado sem expectativa de que seja consumido. Permita olhar, cheirar, tocar, brincar. Divida em etapas progressivas que podem levar dias ou semanas. Nunca force a ingestão. Comemore cada pequena aproximação.",
        faixa_etaria: { min: 2, max: 10 },
        nivel_tea: [1, 2, 3],
        beneficios: ["ampliacao_do_repertorio_alimentar", "reducao_da_aversao_sensorial", "autonomia_alimentar"],
        evitar_se: ["restricao_alimentar_por_prescricao_medica"],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 12,
        materiais: ["alimentos variados", "pratinho de apresentacao", "toalha umida"],
        areas_interesse: ["alimentacao", "sensorial"],
        objetivos: ["dessensibilizacao_alimentar", "ampliacao_alimentar", "autonomia"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["alimentacao", "sensorial", "paciencia", "rotina"]
    },

    {
        nome: "Preparar a Comida Junto",
        descricao: "Envolvimento da criança em tarefas simples e seguras do preparo dos alimentos para aumentar a familiaridade e reduzir a estranheza na hora de comer.",
        como_fazer: "Inclua a criança em tarefas como lavar frutas, misturar ingredientes, apertar o espremedor, montar o prato. Nomeie tudo e converse sobre cores, cheiros e texturas. Comece com alimentos já aceitos e introduza novos gradualmente.",
        faixa_etaria: { min: 2, max: 10 },
        nivel_tea: [1, 2],
        beneficios: ["familiaridade_com_alimentos", "autonomia", "desenvolvimento_da_linguagem", "habilidades_motoras_finas", "autoestima"],
        evitar_se: [],
        nivel_barulho: "baixo",
        nivel_baguncia: "medio",
        tempo_minutos: 30,
        materiais: ["alimentos adequados a idade", "colher de pau", "espatula de borracha", "avental"],
        areas_interesse: ["alimentacao", "culinaria"],
        objetivos: ["aceitacao_alimentar", "autonomia", "estimulacao_da_linguagem"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["alimentacao", "autonomia", "culinaria", "familia"]
    },

    {
        nome: "Prato Colorido como Jogo",
        descricao: "Tornar a refeição mais lúdica propondo um jogo de cores no prato, com pequenas recompensas simbólicas para cada nova cor experimentada.",
        como_fazer: "Monte o prato com alimentos de cores diferentes e transforme em jogo: 'quantas cores tem no seu prato hoje?', 'vamos colocar 3 cores?'. Use recompensas simbólicas como figurinhas. Use prato com divisórias para crianças que têm aversão a alimentos que se tocam.",
        faixa_etaria: { min: 2, max: 9 },
        nivel_tea: [1, 2],
        beneficios: ["diversificacao_alimentar", "reducao_da_ansiedade_na_refeicao", "conceito_de_cores", "autonomia_alimentar"],
        evitar_se: ["restricao_alimentar_por_prescricao_medica"],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 20,
        materiais: ["alimentos de cores variadas", "prato com divisorias", "figurinhas de recompensa"],
        areas_interesse: ["alimentacao", "jogos"],
        objetivos: ["aceitacao_alimentar", "diversificacao_de_cores_e_texturas", "reducao_de_ansiedade"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["alimentacao", "cores", "ludico", "refeicao"]
    },

    {
        nome: "Enfiar Macarrão em Palitos",
        descricao: "Atividade estruturada de coordenação fina em que a criança encaixa macarrão cru em palitos fixados em uma base, criando esculturas.",
        como_fazer: "Fixe palitos na base na vertical. Entregue o macarrão e mostre como encaixar cada peça. Comece com palitos mais grossos e macarrão de orifício maior. Crie desafios de sequência de cores. O resultado pode virar uma escultura para expor.",
        faixa_etaria: { min: 3, max: 9 },
        nivel_tea: [1, 2, 3],
        beneficios: ["pinca_fina", "coordenacao_olho_mao", "concentracao", "planejamento_motor", "sequenciamento"],
        evitar_se: ["comportamento_de_levar_tudo_a_boca_sem_supervisao"],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 20,
        materiais: ["macarrao cru tubular", "palitos de churrasco", "base de isopor ou massinha"],
        areas_interesse: ["construcao", "desafios"],
        objetivos: ["coordenacao_motora_fina", "pinca_digital", "atencao_sustentada"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["motor_fino", "concentracao", "calmo", "estruturado"]
    },

    {
        nome: "Rasgar e Colar Papéis — Mosaico",
        descricao: "Atividade de colagem criativa em que a criança rasga papéis coloridos em pedaços e os cola sobre uma base para formar mosaico ou colagem livre.",
        como_fazer: "Incentive a criança a rasgar os papéis em pedaços pequenos e irregulares. Cole-os sobre a base para formar mosaico ou preencher um contorno. Não corrija a forma de colar — o processo é mais importante que o resultado. Para aversão à cola, use cola bastão.",
        faixa_etaria: { min: 2, max: 9 },
        nivel_tea: [1, 2, 3],
        beneficios: ["forca_de_preensao", "coordenacao_bimanual", "criatividade", "tolerancia_a_texturas", "autoexpressao"],
        evitar_se: ["hipersensibilidade_tatil_severa"],
        nivel_barulho: "baixo",
        nivel_baguncia: "medio",
        tempo_minutos: 30,
        materiais: ["revistas velhas", "papel crepom", "papel colorido", "cola bastao ou cola liquida", "base em papelao ou A3"],
        areas_interesse: ["artes", "criatividade"],
        objetivos: ["coordenacao_motora_fina", "coordenacao_bimanual", "expressao_criativa"],
        fonte: "Guia de Atividades para TEA — uso domiciliar",
        tags: ["motor_fino", "artes", "criatividade", "texturas"]
    },

    {
        nome: "Jogo de Imitação Corporal (Espelho)",
        descricao: "Atividade de imitação em que o adulto faz movimentos simples e a criança repete, como em um espelho, para estimular a atenção compartilhada e a comunicação não verbal.",
        como_fazer: "Sente-se de frente para a criança. Faça movimentos simples com braços, cabeça ou expressões faciais e peça que ela repita. Depois, inverta: deixe a criança liderar e você imite. Celebre cada imitação com entusiasmo. Comece com movimentos grandes e vá refinando.",
        faixa_etaria: { min: 1, max: 6 },
        nivel_tea: [1, 2, 3],
        beneficios: ["atencao_compartilhada", "imitacao_motora", "vinculo_social", "comunicacao_nao_verbal", "consciencia_corporal"],
        evitar_se: [],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 15,
        materiais: [],
        areas_interesse: ["interacao_social", "movimento"],
        objetivos: ["estimulacao_da_imitacao", "atencao_conjunta", "vinculo_com_cuidador"],
        fonte: "Terapia de Integração Sensorial / ABA adaptada",
        tags: ["imitacao", "vinculo", "social", "simples"]
    },

    {
        nome: "Bolinha de Sabão",
        descricao: "Atividade lúdica de soprar bolinhas de sabão para estimular o controle do sopro, o rastreamento visual e a atenção, além de promover interação social e alegria.",
        como_fazer: "Sopre as bolinhas de sabão e encoraje a criança a estourar, perseguir ou soprar também. Nomeie o que acontece: 'a bolinha está flutuando!', 'estoura!'. Encoraje a criança a tentar soprar ela mesma com o aro. A atividade em si já gera atenção compartilhada naturalmente.",
        faixa_etaria: { min: 1, max: 6 },
        nivel_tea: [1, 2, 3],
        beneficios: ["controle_do_sopro", "rastreamento_visual", "atencao_compartilhada", "alegria_e_motivacao", "pre_requisito_para_fala"],
        evitar_se: [],
        nivel_barulho: "baixo",
        nivel_baguncia: "medio",
        tempo_minutos: 15,
        materiais: ["solucao de bolinha de sabao", "aro para bolinha"],
        areas_interesse: ["sensorial", "jogos"],
        objetivos: ["controle_respiratorio", "atencao_visual", "interacao_social"],
        fonte: "Terapia de Fala e Linguagem — atividades de sopro",
        tags: ["sopro", "fala", "alegria", "social", "simples"]
    },

    {
        nome: "Encaixe de Tampinhas por Cor ou Tamanho",
        descricao: "Atividade de classificação e coordenação fina usando tampinhas de garrafa para separar por cor, tamanho ou tipo em recipientes correspondentes.",
        como_fazer: "Reúna tampinhas variadas e potes ou caixinhas etiquetadas por cor ou tamanho. Mostre como classificar e deixe a criança continuar. Comece com apenas duas categorias e aumente gradualmente. Nomeie as cores e quantidades durante a atividade.",
        faixa_etaria: { min: 2, max: 7 },
        nivel_tea: [1, 2, 3],
        beneficios: ["coordenacao_motora_fina", "classificacao_e_categorias", "atencao_sustentada", "conceito_de_cores", "logica"],
        evitar_se: ["comportamento_de_levar_tudo_a_boca_sem_supervisao"],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 15,
        materiais: ["tampinhas de garrafa de cores e tamanhos variados", "potes ou caixinhas"],
        areas_interesse: ["jogos", "construcao"],
        objetivos: ["coordenacao_motora_fina", "classificacao", "atencao_e_concentracao"],
        fonte: "Terapia Ocupacional Pediátrica — atividades domiciliares",
        tags: ["motor_fino", "cores", "estruturado", "calmo", "simples"]
    },

    {
        nome: "Comunicação por Figuras (PECS simplificado)",
        descricao: "Atividade de comunicação alternativa em que a criança usa figuras ou cartões de imagens para expressar desejos e necessidades de forma funcional.",
        como_fazer: "Crie ou imprima cartões com imagens de objetos do cotidiano (água, comida, brinquedo favorito, banheiro). Apresente os cartões durante situações reais de necessidade. Quando a criança apontar ou entregar o cartão, responda imediatamente e nomeie: 'água! você quer água!'.",
        faixa_etaria: { min: 2, max: 8 },
        nivel_tea: [2, 3],
        beneficios: ["comunicacao_alternativa", "reducao_da_frustracao", "intencionalidade_comunicativa", "vocabulario_funcional"],
        evitar_se: [],
        nivel_barulho: "baixo",
        nivel_baguncia: "baixo",
        tempo_minutos: 20,
        materiais: ["cartoes com figuras impressas ou desenhadas", "velcro ou pasta organizadora"],
        areas_interesse: ["comunicacao", "rotina"],
        objetivos: ["comunicacao_funcional", "reducao_de_frustracao", "estimulacao_pre_verbal_e_verbal"],
        fonte: "Sistema PECS — Frost & Bondy (adaptado para uso domiciliar)",
        tags: ["comunicacao", "fala", "alternativo", "rotina", "estruturado"]
    }
]